### ISSUE TITLE
Translation "ERROR"s?

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#59]
Is there any reason we're only displaying errors as the translation fallback? Why couldn't this be the english strings making this more or less error-proof?

**Comment by preip** [comment]
Well... the translation should indeed use english strings as a fallback, the display of the errors is just a fallback for the fallback to prevent the server from crashing. The reasen this didn't happen was beacause of a bug, which should now be fixed. (I just spelled dictionary wrong... damn you, runtime validation)

**Comment by kiliankoe** [comment]
This is not what I meant. 

```
p.lead
    = dict === undefined ? 'ERROR' : dict.get('home', 'intro2')
```

Here for example, the default case is always 'ERROR' and then it loads the dictionary. Why don't we replace 'ERROR' with the english strings therefore being prone to errors where it can't find the database (even if that's probably never going to come up), but also making the code in the views more readable.

**Comment by preip** [comment]
Well you can if you like, but this should indeed never happen. I thought about using the english strings, but did not for three reasons:
a) If there's an error loading the dictionaries it would be hard to notice, because everything would display correct anyway (at least if english is your normal language). This could be circumvented by posting error messages to the log, if dictionaries fail to load.
b) Everything would be duplicated from the strings in the dictionaries, so if one would change something in the dictionary you need to also change it in the views, or it wouldn't be consistent.
c) It's only there to prevent the server from crashing if the dictionary could not be loaded. So adding more text would really just cluttering up the view. (The readability of the views will be better, if some comments are added, not by expanding the text for the fallback case.)

These were my main concerns, but they are of course debatable.
Speaking of the database: That is another interesting point. We could put the whole dictionaries in the database, because we already have one. The question is, if we would gain something by doing that, or not.

**Comment by kiliankoe** [comment]
> Speaking of the database: That is another interesting point. We could put the whole dictionaries in the database, because we already have one. The question is, if we would gain something by doing that, or not.

Probably not, as they would no longer be under version control. 

But the rest are valid points, my only concern was towards the readability of the views, but a few comments should help out there.

I'll just go ahead and close this issue then.
