### ISSUE TITLE
Secure data behind a login

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#9]
Simplest approach: htaccess

Something of ours would be nicer though.

**Comment by preip** [comment]
so, while this is basically finished, there are still a few issues.
For a start, i will move all POST requests behind the authentication too and hope that nothing breaks. I will also build a page where it's possible to change an account password or delete the account. New accounts can only be created by an user, which is already logged into the system.

From my perspective, it would be reasonable to make the admin account some kind of special account, which a) can't be removed and b) is the only account which can create new accounts.
Since we don't have (and probably don't need) a role system inside the application, this would be more or less hardcoded.
Is everybody fine with that, or has someone a different idea?

**Comment by kiliankoe** [comment]
Fine with all of it :+1:

**Comment by preip** [comment]
After asking an ... uh ... idependent security consultant, I was made aware of a tiny little weakness in the current design, which is sending the passwords in plaintext to the server and hashing them there. What I should have done is sending the salt from server to client, hashing the password on the client side an sending the resulting hash to the server. The result is that the password is never exposed to the server in plain text.
As a sidenode to the system in general: restoring password if they have been forgotten is out of question. The only possible solution is to reset them to a random string, that can then be send to the user, which i might implement at some point in the future.

**Comment by kiliankoe** [comment]
Restoring passwords is never a good idea, as it clearly shows that a service has access to your password in plaintext. Letting a user choose a new random password is always the better option.

**Comment by preip** [comment]
Hashing the passwords client site is done. It works a little differently than usually planned:
If the user types it's password, a hash for that password is generated with cha256. If the user clicks the submit button, the hash is send to server, which concatenates the salt and the pwd and hashes the result.

Furthermore are either of the change password, delete account and create a new account functionality working.
